### ISSUE TITLE
Add Resource Request: WebPower online tool

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#29]
<strong>What is the resource called?: </strong>
WebPower online tool

<strong>What is the link to the resource?: </strong>
https://webpower.psychstat.org/wiki/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
WebPower is a collection of tools for conducting statistical power analysis online. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Study design

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
study design, sample size

**Comment by alkastrinogiannis** [comment]
Added
