### ISSUE TITLE
Add Resource Request: Improving Statistical Questions by Daniel Lakens

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#31]
<strong>What is the resource called?: </strong>
Improving Statistical Questions by Daniel Lakens

<strong>What is the link to the resource?: </strong>
https://www.coursera.org/learn/improving-statistical-questions

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
The course aims to help you to ask better statistical questions when performing empirical research

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Project start > Literature

**Comment by alkastrinogiannis** [comment]
Added
