### ISSUE TITLE
Add Resource Request: Big Team Setup

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#32]
<strong>What is the resource called?: </strong>
Big Team Setup

<strong>What is the link to the resource?: </strong>
https://debruine.github.io/big-team-setup/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
This guide is aimed at people wanting to start a big team science group from the grassroots, with little or no financial or administrative support. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Project start > Organisation

**Comment by alkastrinogiannis** [comment]
Added
