### ISSUE TITLE
Add Resource Request: Brain Interpreter

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#33]
<strong>What is the resource called?: </strong>
Brain Interpreter

<strong>What is the link to the resource?: </strong>
https://braininterpreter.com/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
An artificial neural network that predicts brain activation maps from snippets of text.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Project start > Literature

**Comment by alkastrinogiannis** [comment]
Added
