### ISSUE TITLE
Add Resource Request: neurosynth compose

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#34]
<strong>What is the resource called?: </strong>
neurosynth compose

<strong>What is the link to the resource?: </strong>
https://compose.neurosynth.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Perform custom neuroimaging meta-analyses entirely in the browser, and quickly get results in the cloud using automated analysis pipelines.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Study design

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Study design > Imaging data

**Comment by alkastrinogiannis** [comment]
Added
