### ISSUE TITLE
Add Resource Request: Preprocessing guidelines for psychophysiological outcomes

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#35]
<strong>What is the resource called?: </strong>
Preprocessing guidelines for psychophysiological outcomes

<strong>What is the link to the resource?: </strong>
https://sprweb.org/general/custom.asp?page=Guidelines_Papers

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
This is a collection of helpful papers and guidelines on how to preprocess different psychophysiological data.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Data validation

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Data validation --> Preprocessing

**Comment by alkastrinogiannis** [comment]
Added
