### ISSUE TITLE
Add Resource Request: Octopus

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#36]
<strong>What is the resource called?: </strong>
Octopus

<strong>What is the link to the resource?: </strong>
https://www.octopus.ac/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Octopus is a free pulishing platform for scholarly research, including peer review and quality assessment.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Publication

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
just under Publication

**Comment by alkastrinogiannis** [comment]
Added
