### ISSUE TITLE
Add Resource Request: DataCite

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#40]
<strong>What is the resource called?: </strong>
DataCite

<strong>What is the link to the resource?: </strong>
https://datacite.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
ensure that research outputs andDataCite ensures that resources are openly available and connected

<strong>Which step of the research cycle does the resource belong to?: </strong>
Dissemination

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Closed (i.e. you have to pay or subscribe to use the resource)

**Comment by alkastrinogiannis** [comment]
Added
