### ISSUE TITLE
Add Resource Request: figshare

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#41]
<strong>What is the resource called?: </strong>
figshare

<strong>What is the link to the resource?: </strong>
https://figshare.com/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
The all in one repository - a home for papers, FAIR data and non-traditional research outputs that is easy to use and ready now.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Dissemination

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
