### ISSUE TITLE
Add Resource Request: Open Access Button

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#42]
<strong>What is the resource called?: </strong>
Open Access Button

<strong>What is the link to the resource?: </strong>
https://openaccessbutton.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Free, legal research articles delivered instantly or automatically requested from authors.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Where exactly under Project start?

**Comment by helenahartmann** [comment]
Literature!

**Comment by alkastrinogiannis** [comment]
Added
