### ISSUE TITLE
Add Resource Request: PreReview

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#43]
<strong>What is the resource called?: </strong>
PreReview

<strong>What is the link to the resource?: </strong>
https://prereview.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Provide and receive constructive feedback on preprints from an international community of your peers.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Publication

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
