### ISSUE TITLE
Add Resource Request: Protocols

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#45]
<strong>What is the resource called?: </strong>
Protocols

<strong>What is the link to the resource?: </strong>
https://www.protocols.io/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
A secure platform for developing and sharing reproducible methods.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Dissemination

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Hybrid (i.e., there is a free and a paid version of the resource)

**Comment by alkastrinogiannis** [comment]
Added
