### ISSUE TITLE
Add Resource Request: Center for Open Science

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#48]
<strong>What is the resource called?: </strong>
Center for Open Science

<strong>What is the link to the resource?: </strong>
https://www.cos.io/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Their mission is to increase openness, integrity, and reproducibility of research.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
