### ISSUE TITLE
Add Resource Request: Database of Open Science communities

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#49]
<strong>What is the resource called?: </strong>
Database of Open Science communities

<strong>What is the link to the resource?: </strong>
https://docs.google.com/spreadsheets/d/1CuO7ZjJUuMGvvMmRfnXfPbvTnfWc5lO4oFE2U22nAic/edit?gid=1718200050#gid=1718200050

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
A list of communities promoting/impacted by open science practices.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
