### ISSUE TITLE
Add Resource Request: International Network of Open Science & Scholarship Communities

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#50]
<strong>What is the resource called?: </strong>
International Network of Open Science & Scholarship Communities

<strong>What is the link to the resource?: </strong>
https://osc-international.com/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
INOSC is an international network of local Open Science & Open Scholarship communities (OSC). OSCs are hubs where academics learn from their peers how to make their workflows more open. More and more academics are joining OSCs, ready to put Open Science to practice.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
