### ISSUE TITLE
Add Resource Request: PsychOpen CAMA

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#51]
<strong>What is the resource called?: </strong>
PsychOpen CAMA

<strong>What is the link to the resource?: </strong>
https://cama.psychopen.eu/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
PsychOpen CAMA enables accessing meta-analytic datasets, reproducing meta-analyses and dynamically updating evidence from new primary studies collaboratively.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Study design

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
