### ISSUE TITLE
Add Resource Request: Global Reproducibility Networks

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#52]
<strong>What is the resource called?: </strong>
Global Reproducibility Networks

<strong>What is the link to the resource?: </strong>
https://www.ukrn.org/global-networks/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
A Reproducibility Network (RN) is a national, peer-led consortium of researchers that aims to promote and ensure rigorous research practices by establishing appropriate training activities, designing and evaluating research improvement efforts, disseminating best practice and working with stakeholders to coordinate efforts across the sector. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
