### ISSUE TITLE
Add Resource Request: ReproducibiliTea

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#53]
<strong>What is the resource called?: </strong>
ReproducibiliTea

<strong>What is the link to the resource?: </strong>
https://reproducibilitea.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
A grassroots journal club initiative that helps researchers create local Open Science journal clubs at their universities to discuss diverse issues, papers and ideas about improving science, reproducibility and the Open Science movement. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
