### ISSUE TITLE
Add Resource Request: The Society for the Improvement of Psychological Science

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#54]
<strong>What is the resource called?: </strong>
The Society for the Improvement of Psychological Science

<strong>What is the link to the resource?: </strong>
https://improvingpsych.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Brings together scholars working to improve methods and practices in psychological science. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
