### ISSUE TITLE
Add Resource Request: Pint of Science

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#56]
<strong>What is the resource called?: </strong>
Pint of Science

<strong>What is the link to the resource?: </strong>
https://pintofscience.com/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
Pint of Science is non-profit and organised by a grass-root community of thousands of scientists across the world, organizing events for the public to hear about and question the latest discoveries being made.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Dissemination

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Open (i.e., everything in the resource is free and open to use)

**Comment by alkastrinogiannis** [comment]
Added
