### ISSUE TITLE
Add Resource Request: Psychological Science Accelerator

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#58]
<strong>What is the resource called?: </strong>
Psychological Science Accelerator

<strong>What is the link to the resource?: </strong>
https://psysciacc.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
a globally distributed network of researchers that pool intellectual and material resources to accelerate the accumulation of rigorous knowledge in psychological science.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>Please judge the accessibility of the resource: </strong>
Open (i.e., everything in the resource is free and open to use)

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
project start - communities

**Comment by alkastrinogiannis** [comment]
Added
