### ISSUE TITLE
Add Resource Request: The Turing Way

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#59]
<strong>What is the resource called?: </strong>
The Turing Way

<strong>What is the link to the resource?: </strong>
https://book.the-turing-way.org/

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
An open science, open collaboration, and community-driven project. We involve and support a diverse community of contributors to make data science accessible, comprehensible and effective for everyone. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Project start

<strong>Please judge the accessibility of the resource: </strong>
Open (i.e., everything in the resource is free and open to use)

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
project start - communities

**Comment by alkastrinogiannis** [comment]
Added
