### ISSUE TITLE
Add Resource Request: DataWeasel

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#69]
<strong>What is the resource called?: </strong>
DataWeasel

<strong>What is the link to the resource?: </strong>
https://www.uni-giessen.de/de/fbz/fb11/institute/psychiatrie/down/dawe

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
This software allows for logfile analysis, i.e., searching, filtering, calculating, and batch mode with a graphical user interface.

<strong>Which step of the research cycle does the resource belong to?: </strong>
Data analysis

<strong>Please judge the accessibility of the resource: </strong>
Open (i.e., everything in the resource is free and open to use)

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Data analysis > Data extraction > ...

**Comment by alkastrinogiannis** [comment]
added
