### ISSUE TITLE
Add Resource Request: juicr

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#70]
<strong>What is the resource called?: </strong>
juicr

<strong>What is the link to the resource?: </strong>
https://github.com/mjlajeunesse/juicr

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
juicr is a GUI interface to automated, semi-automated, and manual tools for extracting data from scientific images -- like scatter or bar plots that contain data, or other images with information that can be converted numerically or coordinates classified. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Data analysis

<strong>Please judge the accessibility of the resource: </strong>
Open (i.e., everything in the resource is free and open to use)

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Data analysis > Data extraction > ...

**Comment by alkastrinogiannis** [comment]
added
