### ISSUE TITLE
Add Resource Request: shinyDigitise

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#71]
<strong>What is the resource called?: </strong>
shinyDigitise

<strong>What is the link to the resource?: </strong>
https://github.com/EIvimeyCook/shinyDigitise/tree/master

<strong>Please provide a short description of the resource (1-3 sentences): </strong>
shinyDigitise is an R package that builds upon the popular metaDigitise package and provides users with an interactive UI to help extraction of data from five different plot types. 

<strong>Which step of the research cycle does the resource belong to?: </strong>
Data analysis

<strong>Please judge the accessibility of the resource: </strong>
Open (i.e., everything in the resource is free and open to use)

<strong>If possible, please provide the exact path where you want this resource to go?: </strong>
Data analysis > Data extraction > ...

**Comment by alkastrinogiannis** [comment]
added
