### ISSUE TITLE
Bug Report: Hi there! There seems to be a tiny mistake in the instructions part: the description of the lock with key and the open lock are identical.

### ISSUE THREAD

**Issue by caggursoy** [IGOR-bioDGPs/ARIADNE#78]
<strong>Describe the bug: </strong>
Hi there! There seems to be a tiny mistake in the instructions part: the description of the lock with key and the open lock are identical.

<strong>Expected behavior: </strong>
The description of the lock with key needs to be adapted.

<strong>Desktop information (please complete the following information):: </strong>
Windows, Firefox browser

<strong>Additional context: </strong>

**Comment by alkastrinogiannis** [comment]
fixed
